# Generated by Django 5.2.7 on 2025-12-17 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="pokemon_entities/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PokemonEntity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField(verbose_name="Широта")),
                ("longitude", models.FloatField(verbose_name="Долгота")),
                ("appeared_at", models.DateTimeField(verbose_name="Появится")),
                ("disappeared_at", models.DateTimeField(verbose_name="Исчезнит")),
                ("level", models.FloatField(default=0)),
                ("health", models.FloatField(default=0)),
                ("strength", models.FloatField(default=0)),
                ("defence", models.FloatField(default=0)),
                ("stamina", models.FloatField(default=0)),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities",
                        to="pokemon_entities.pokemon",
                        verbose_name="Тип покемона",
                    ),
                ),
            ],
        ),
    ]
