# Generated by Django 5.2.7 on 2026-02-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemonentity",
            name="defence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="health",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="level",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="stamina",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="strength",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
