# Generated by Django 5.2.7 on 2026-02-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0002_alter_pokemonentity_defence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="name_en",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="name_ja",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
