# Generated by Django 5.2.7 on 2026-02-18 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0003_pokemon_name_en_pokemon_name_ja"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pokemon",
            old_name="name_en",
            new_name="title_en",
        ),
        migrations.RenameField(
            model_name="pokemon",
            old_name="name_ja",
            new_name="title_jp",
        ),
        migrations.RenameField(
            model_name="pokemon",
            old_name="title",
            new_name="title_ru",
        ),
        migrations.AddField(
            model_name="pokemon",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="previous_evolution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_evolutions",
                to="pokemon_entities.pokemon",
            ),
        ),
    ]
