# Generated by Django 5.2.7 on 2026-02-23 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0004_rename_name_en_pokemon_title_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание покемона"),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="previous_evolution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_evolutions",
                to="pokemon_entities.pokemon",
                verbose_name="Эволюция покемона",
            ),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="название покемона англ."
            ),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="title_jp",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="название покемона япон."
            ),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="title_ru",
            field=models.CharField(
                max_length=200, verbose_name="Название покемона рус."
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="appeared_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Появится"),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="defence",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Защита покемона"
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="disappeared_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Исчезнит"),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="health",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Здоровье покемона"
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Широта"),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="level",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Уровень покемона"
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Долгота"),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="stamina",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Выносливость покемона"
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="strength",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Сила покемона"
            ),
        ),
    ]
